/**:
  ros__parameters:
    stretch_waypoints: [0.0, 0.0]
    d435_poses_pan: [
      -2.09,
      -2.09,
      -1.83,
      -1.83,
      -1.57,
      -1.57,
      -1.31,
      -1.31,
      -1.05,
      -1.05,
      -0.79,
      -0.79]
    d435_poses_tilt: [
      0.0,
      -0.3,
      0.0,
      -0.3,
      0.0,
      -0.3,
      0.0,
      -0.3,
      0.0,
      -0.3,
      0.0,
      -0.3]
    d405_poses_lift: [0.3,
      0.6]
    d405_poses_tilt: [0.0,
      0.25]
    d405_poses_yaw: [0.1,
      -0.1]
    run_num: 9
    
